Update report.yml

diff --git a/.github/workflows/report.yml b/.github/workflows/report.yml
--- a/.github/workflows/report.yml
+++ b/.github/workflows/report.yml
@@ -1,51 +1,47 @@
-# .github/workflows/ci.yml
-
 name: Python Tests
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ main ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ main ]
 
 jobs:
   test:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
-    
-    - name: Print current directory
-      run: pwd
-    
-    - name: List files in the directory
-      run: ls -R
-    
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.10'  # Adjust Python version as needed
-    
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pytest pytest-markdown-docs
-    
-    - name: Verify file presence
-      run: |
-        if [ ! -f ".github/workflows/test_calculator.py" ]; then
-          echo "File .github/workflows/test_calculator.py not found!"
-          exit 1
-        fi
-    
-    - name: Run tests and generate markdown report
-      run: |
-        pytest .github/workflows/test_calculator.py --md pytest_report.md
-    
-    - name: Display markdown report
-      run: |
-        echo "## Pytest Markdown Report"
-        echo '```markdown'
-        cat pytest_report.md
-        echo '```'
+      - uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest pytest-markdown-docs
+
+      - name: Print pytest version
+        run: pytest --version
+
+      - name: Print pytest-markdown-docs version
+        run: pytest --version --md
+
+      - name: Verify file presence
+        run: |
+          if [ ! -f ".github/workflows/test_calculator.py" ]; then
+            echo "File .github/workflows/test_calculator.py not found!"
+            exit 1
+          fi
+
+      - name: Run tests and generate markdown report
+        run: pytest .github/workflows/test_calculator.py --md --md-file=pytest_report.md
+
+      - name: Display markdown report
+        run: |
+          echo "## Pytest Markdown Report"
+          echo '```markdown'
+          cat pytest_report.md
+          echo '```'
